### ISSUE TITLE
Avoid TypeError

### ISSUE THREAD

**Issue by adius** [brickify/stl-parser#19]
```
$ cat ~/Projects/stl-models/broken/missingNormal.ascii.stl | stl-parser
{ _: [], '$0': '/usr/local/bin/stl-parser' }
{"name":"tetrahedron","isClosed":false}
{"number":1,"normal":{"x":0,"y":0,"z":-1},"vertices":[{"x":0,"y":0,"z":0},{"x":0,"y":1,"z":0},{"x":1,"y":0,"z":0}]}
{"number":2,"normal":{"x":0,"y":-1,"z":0},"vertices":[{"x":0,"y":0,"z":0},{"x":1,"y":0,"z":0},{"x":0,"y":0,"z":1}]}
{"number":3,"normal":{"x":-1,"y":0,"z":0},"vertices":[{"x":0,"y":0,"z":0},{"x":0,"y":0,"z":1},{"x":0,"y":1,"z":0}]}
Error: Unexpected vertex after normal-y in face 4 in line 25
    at AsciiParser._transform (/Users/adrian/Projects/stl-parser/build/AsciiParser.js:149:32)
    at AsciiParser._transform (/Users/adrian/Projects/stl-parser/build/AsciiParser.js:4:59)
    at AsciiParser.Transform._read (_stream_transform.js:179:10)
    at AsciiParser.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at AsciiParser.Writable.write (_stream_writable.js:217:11)
    at StlParser._transform (/Users/adrian/Projects/stl-parser/build/StlParser.js:80:26)
    at StlParser.Transform._read (_stream_transform.js:179:10)
    at StlParser.Transform._write (_stream_transform.js:167:12)
/Users/adrian/Projects/stl-parser/build/AsciiParser.js:147
            this.currentFace.vertices.push(this.currentVertex);
                                     ^
TypeError: Cannot read property 'push' of undefined
    at AsciiParser._transform (/Users/adrian/Projects/stl-parser/build/AsciiParser.js:147:38)
    at AsciiParser._transform (/Users/adrian/Projects/stl-parser/build/AsciiParser.js:4:59)
    at AsciiParser.Transform._read (_stream_transform.js:179:10)
    at AsciiParser.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at AsciiParser.Writable.write (_stream_writable.js:217:11)
    at StlParser._transform (/Users/adrian/Projects/stl-parser/build/StlParser.js:80:26)
    at StlParser.Transform._read (_stream_transform.js:179:10)
    at StlParser.Transform._write (_stream_transform.js:167:12)
```

**Comment by adius** [comment]
Fixed in ab47a0dd3455ea770a1343c144a5e4e34a1ba83d
